using Microsoft.AspNetCore.Razor.Language;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.Extensions.Logging;

namespace XmlReportGenerator.Blazor.Services;

/// <summary>
/// Validates a Blazor component (.razor) generated by AI using the Roslyn compiler.
/// </summary>
public class RazorValidator
{
    private readonly ILogger<RazorValidator> _logger;

    /// <summary>
    /// Initializes a new instance of <see cref="RazorValidator"/>.
    /// </summary>
    /// <param name="logger">The logger.</param>
    public RazorValidator(ILogger<RazorValidator> logger)
    {
        _logger = logger;
    }

    /// <summary>
    /// Validates the provided Razor component content for syntax and compilation errors.
    /// </summary>
    /// <param name="razorContent">The .razor file content to validate.</param>
    /// <returns>
    /// A tuple where <c>IsValid</c> indicates success and <c>Errors</c> contains any diagnostics.
    /// </returns>
    public (bool IsValid, IReadOnlyList<string> Errors) Validate(string razorContent)
    {
        if (string.IsNullOrWhiteSpace(razorContent))
            return (false, new[] { "Razor content cannot be null or empty." });

        var errors = new List<string>();

        try
        {
            // Use Razor Language to parse and generate C# code from the .razor component
            var fileSystem = RazorProjectFileSystem.Create(".");
            var projectEngine = RazorProjectEngine.Create(
                RazorConfiguration.Default,
                fileSystem,
                builder => builder.SetRootNamespace("XmlReportGenerator.GeneratedComponents"));

            var sourceDocument = RazorSourceDocument.Create(razorContent, "GeneratedComponent.razor");
            var codeDocument = projectEngine.Process(
                sourceDocument,
                fileKind: null,
                importSources: null,
                tagHelpers: null);

            // Check Razor diagnostics from the C# document
            var csharpDocument = codeDocument.GetCSharpDocument();
            foreach (var diagnostic in csharpDocument.Diagnostics)
            {
                if (diagnostic.Severity == RazorDiagnosticSeverity.Error)
                    errors.Add($"Razor error: {diagnostic.GetMessage()}");
            }

            if (errors.Count > 0)
                return (false, errors.AsReadOnly());

            // Generate C# from the Razor document and compile with Roslyn
            var generatedCode = csharpDocument.GeneratedCode;

            var syntaxTree = CSharpSyntaxTree.ParseText(generatedCode);
            var compilation = CSharpCompilation.Create(
                assemblyName: "GeneratedRazorComponent",
                syntaxTrees: new[] { syntaxTree },
                references: GetMetadataReferences(),
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            var diagnostics = compilation.GetDiagnostics()
                .Where(d => d.Severity == DiagnosticSeverity.Error)
                .ToList();

            foreach (var diagnostic in diagnostics)
                errors.Add($"Roslyn error: {diagnostic.GetMessage()}");

            var isValid = errors.Count == 0;

            if (isValid)
                _logger.LogInformation("Razor component validation passed.");
            else
                _logger.LogWarning("Razor component validation failed with {Count} error(s).", errors.Count);

            return (isValid, errors.AsReadOnly());
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Exception during Razor validation.");
            return (false, new[] { $"Validation exception: {ex.Message}" });
        }
    }

    private static IEnumerable<MetadataReference> GetMetadataReferences()
    {
        var references = new List<MetadataReference>();

        // Add core runtime references
        var trustedAssemblies = AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") as string;
        if (trustedAssemblies != null)
        {
            foreach (var assembly in trustedAssemblies.Split(Path.PathSeparator))
            {
                if (File.Exists(assembly))
                    references.Add(MetadataReference.CreateFromFile(assembly));
            }
        }

        return references;
    }
}
